spring:
  zipkin:
    base-url: http://116.62.156.171:8082
  boot:
    admin:
      client:
        url: http://120.24.95.233:8083
  output:
        ansi:
          enabled: always
eureka:
    client:
      register-with-eureka: true
      service-url:
          defaultZone: http://116.62.156.171:8761/eureka/
    instance:
      instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
      prefer-ip-address: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"