spring:
  application:
    name: ecs-zipkin
  main:
      allow-bean-definition-overriding: true
  boot:
      admin:
        client:
          url: http://94.191.119.1927:8084

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.lhz520.cn:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
