spring:
  application:
    name: ecs-zipkin
  main:
      allow-bean-definition-overriding: true
  boot:
      admin:
        client:
          url: http://94.191.119.192:8083
          instance:
            service-base-url: http://94.191.119.192:8082

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.lhz520.cn:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: /root/ecs/zipkin-logs.log
  level:
    cn.lhz: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"