spring:
  application:
    name: ecs-admin
  zipkin:
    base-url: http://116.62.156.171:8082
  output:
      ansi:
        enabled: always


server:
  port: 8083

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        #include: health,info
        include: "*"

eureka:
  client:
    register-with-eureka: true
    service-url:
        defaultZone: http://116.62.156.171:8761/eureka/
  instance:
    health-check-url: http://${eureka.instance.ip-address}:${eureka.instance.non-secure-port}/health
    prefer-ip-address: true
    ip-address: 120.24.95.233
    non-secure-port: 8083
