spring:
  application:
    name: ecs-redis
  boot:
    admin:
      client:
        url: http://120.24.95.233:8083
        instance:
            service-base-url: http://94.191.119.192:8084
  zipkin:
    base-url: http://116.62.156.171:8082
  redis:
   # Redis数据库索引（默认为0）
     database: 0
     # Redis服务器地址
     host: 94.191.119.192
     # Redis服务器连接端口
     port: 7777
     # Redis服务器连接密码（默认为空）
     password:
     jedis:
       pool:
       # 连接池最大连接数（使用负值表示没有限制）
         max-active: 8
         max-idle: 8
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
         max-wait: -1ms
         min-idle: 0
     timeout: 5000

       #shutdown-timeout: 1000
     #sentinel:
       #master: mymaster
       #nodes: 192.168.75.140:26379, 192.168.75.140:26380, 192.168.75.140:26381

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true
    service-url:
        defaultZone: http://116.62.156.171:8761/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
    prefer-ip-address: true
    ip-address: 94.191.119.192
    non-secure-port: 8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"