spring:
  application:
    name: ecs-zipkin
  main:
      allow-bean-definition-overriding: true
  boot:
      admin:
        client:
          url: http://120.24.95.233:8083
          instance:
            service-base-url: http://94.191.119.192:8082
  output:
      ansi:
        enabled: always

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.63.162:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
