spring:
  application:
    name: ecs-zuul
  zipkin:
    base-url: http://116.62.156.171:8082
  boot:
    admin:
      client:
        url: http://120.24.95.233:8083
        instance:
            prefer-ip: true
            service-base-url: http://120.79.63.162:8081
  output:
      ansi:
        enabled: always

eureka:
  client:
    register-with-eureka: true
    service-url:
        defaultZone: http://116.62.156.171:8761/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${eureka.instance.non-secure-port}
    prefer-ip-address: true
    ip-address: 120.79.63.162
    non-secure-port: 8081
server:
  port: 8081


zuul:
  prefix: /api
  routes:
    api-config:
      path: /config/**
      serviceId: ecs-config
    api-zipkin:
      path: /zipkin/**
      serviceId: ecs-zipkin
    api-admin:
      path: /admin/**
      serviceId: ecs-admin
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
