spring:
  application:
    name: ecs-admin
  zipkin:
    base-url: http://94.191.119.192:8082

server:
  port: 8083

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        # 注意：此处在视频里是 include: ["health", "info"] 但已无效了，请修改
        #include: health,info
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.lhz520.cn:8761/eureka/

logging:
  file: /root/ecs/admin-logs.log
  level:
    cn.lhz: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
