spring:
  application:
    name: ecs-zuul
server:
  port: 8081
  address: 120.79.63.162

zuul:
  prefix: /api
  routes:
    api-config:
      path: /config/**
      serviceId: ecs-config
    api-zipkin:
      path: /zipkin/**
      serviceId: ecs-zipkin
    api-admin:
      path: /admin/**
      serviceId: ecs-admin

