#eueka 主机名
eureka:
  instance:
    hostname: ecs-eureka
  client:
  #不注册自己
    register-with-eureka: false
    #获取服务
    fetch-registry: false
    service-url:
    #提供者和消费者的注册地址
     defaultZone: http://116.62.156.171:8761/eureka/
server:
  port: 8761
spring:
  boot:
   admin:
    client:
      url: http://120.24.95.233:8083
      instance:
         service-base-url: http://116.62.156.171:8761
  zipkin:
    base-url: http://116.62.156.171:8082
  output:
      ansi:
        enabled: always
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

