#eueka 主机名
eureka:
  instance:
    hostname: ecs-eureka
  client:
  #不注册自己
    register-with-eureka: false
    #获取服务
    fetch-registry: false
    service-url:
    #提供者和消费者的注册地址
     defaultZone: http://www.lhz520.cn:8761/eureka/
server:
  port: 8761
spring:
  boot:
   admin:
    client:
      url: http://94.191.119.192:8083
      instance:
         service-base-url: http://www.lhz520.cn:8761
  zipkin:
    base-url: http://94.191.119.192:8082
management:
  endpoints:
    web:
      exposure:
        include: "*"