server:
  port: 8099



eureka:
  instance:
    prefer-ip-address: true
  #注册地址
  client:
    service-url:
      defaultZone: http://www.lhz520.cn:8761/eureka/


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://www.lhz520.cn:3306/ESC?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: flase
    testOnReturn: false
    filters: stat,wall,logback
    logSlowSql: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lhz.common.entity

