spring:
  application:
    name: ecs-zipkin
  main:
      allow-bean-definition-overriding: true
  boot:
      admin:
        client:
          url: http://120.24.95.233:8083
          instance:
            service-base-url: http://116.62.156.171:8082
  #彩色日志开启
  output:
      ansi:
        enabled: always

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    service-url:
        defaultZone: http://116.62.156.171:8761/eureka/
  instance:
    health-check-url: http://${eureka.instance.ip-address}:${eureka.instance.non-secure-port}/health
    prefer-ip-address: true
    ip-address: 116.62.156.171
    non-secure-port: 8082

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
