spring:
  application:
    name: ecs-zuul
  boot:
    admin:
      client:
        instance:
            service-base-url: http://120.79.63.162:8081


  instance:
    ip-address: 120.79.63.162
    non-secure-port: 8081
server:
  port: 8081


zuul:
  prefix: /api
  routes:
    api-config:
      path: /config/**
      serviceId: ecs-config
    api-zipkin:
      path: /zipkin/**
      serviceId: ecs-zipkin
    api-admin:
      path: /admin/**
      serviceId: ecs-admin

