spring:
  application:
    name: ecs-sso
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://www.lhz520.cn:3306/ESC?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: flase
    testOnReturn: false
    filters: stat,wall,logback
    logSlowSql: true
  zipkin:
    base-url: http://94.191.119.192:8082
  freemarker:
      #关闭缓存，即时刷新
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      suffix: .ftl
      template-loader-path: classpath:/templates
      request-context-attribute: request
  resources:
    static-locations: classpath:/static
  boot:
    admin:
      client:
        url: http://120.24.95.233:8083
        #instance:
           # service-base-url: http://120.79.63.162:8081
  output:
      ansi:
        enabled: always
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.63.162:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
#feign打开熔断
feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lhz.common.entity
